/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "govSnmp.h"


/*
 * column number definitions for table govSnmpRecordsTable 
 */
#define COLUMN_GOVSNMPRECORDSEMPLOYEEID		1
#define COLUMN_GOVSNMPRECORDSNAME		2
#define COLUMN_GOVSNMPRECORDSGENDER		3
#define COLUMN_GOVSNMPRECORDSDESIGNATION		4
#define COLUMN_GOVSNMPRECORDSSALARY		5

    /*
     * Typical data structure for a row entry 
     */
struct govSnmpRecordsTable_entry {
    /*
     * Index values 
     */
    long            govSnmpRecordsEmployeeID;

    /*
     * Column values 
     */
    char            govSnmpRecordsName[100];
    size_t          govSnmpRecordsName_len;
    char            old_govSnmpRecordsName[100];
    size_t          old_govSnmpRecordsName_len;
    char            govSnmpRecordsGender[5];
    size_t          govSnmpRecordsGender_len;
    char            old_govSnmpRecordsGender[5];
    size_t          old_govSnmpRecordsGender_len;
    char            govSnmpRecordsDesignation[100];
    size_t          govSnmpRecordsDesignation_len;
    char            old_govSnmpRecordsDesignation[100];
    size_t          old_govSnmpRecordsDesignation_len;
    long            govSnmpRecordsSalary;
    long            old_govSnmpRecordsSalary;

    int             valid;
};
// making a global structure - doubly linked list - to prevent file reading - writing task
struct emp{
	struct govSnmpRecordsTable_entry* entry;
	struct emp* prev; 
	struct emp* next;
	//just for practice 
};
static struct emp* header;
static struct emp* tail;
static int MAX_COL = 5;
//hard-coding : creating the initial records
void create(){
	struct emp* temp = (struct emp*)malloc(sizeof(struct emp));
	header = temp;
	tail = temp;
	
	temp->prev = NULL;
        temp->entry = (struct govSnmpRecordsTable_entry*)malloc(sizeof(struct govSnmpRecordsTable_entry));
	temp->entry->govSnmpRecordsEmployeeID = 1;
	strcpy(temp->entry->govSnmpRecordsName , "Shankar");
	strcpy(temp->entry->govSnmpRecordsGender , "M");
	strcpy(temp->entry->govSnmpRecordsDesignation , "Senior Manager");
	temp->entry->govSnmpRecordsSalary = 2000000;
	temp->entry->govSnmpRecordsName_len = strlen(temp->entry->govSnmpRecordsName);
	temp->entry->govSnmpRecordsGender_len = strlen(temp->entry->govSnmpRecordsGender);
	temp->entry->govSnmpRecordsDesignation_len = strlen(temp->entry->govSnmpRecordsDesignation);
	temp->entry->valid = 1;

	temp->next = (struct emp*)malloc(sizeof(struct emp));
	temp->next->prev = temp;
	temp = temp->next;
	temp->entry = (struct govSnmpRecordsTable_entry*)malloc(sizeof(struct govSnmpRecordsTable_entry));
	temp->entry->govSnmpRecordsEmployeeID = 2;
	strcpy(temp->entry->govSnmpRecordsName , "Meera");
	strcpy(temp->entry->govSnmpRecordsGender , "F");
	strcpy(temp->entry->govSnmpRecordsDesignation , "Human Resource Manager");
	temp->entry->govSnmpRecordsSalary = 1250000;
	temp->entry->govSnmpRecordsName_len = strlen(temp->entry->govSnmpRecordsName);
	temp->entry->govSnmpRecordsGender_len = strlen(temp->entry->govSnmpRecordsGender);
	temp->entry->govSnmpRecordsDesignation_len = strlen(temp->entry->govSnmpRecordsDesignation);
	temp->entry->valid = 1;

	temp->next = (struct emp*)malloc(sizeof(struct emp));
	temp->next->prev = temp;
	temp = temp->next;
	temp->entry = (struct govSnmpRecordsTable_entry*)malloc(sizeof(struct govSnmpRecordsTable_entry));
	temp->entry->govSnmpRecordsEmployeeID = 3;
	strcpy(temp->entry->govSnmpRecordsName , "Ram");
	strcpy(temp->entry->govSnmpRecordsGender , "M");
	strcpy(temp->entry->govSnmpRecordsDesignation , "Lead Engineer");
	temp->entry->govSnmpRecordsSalary = 1500000;
	temp->entry->govSnmpRecordsName_len = strlen(temp->entry->govSnmpRecordsName);
	temp->entry->govSnmpRecordsGender_len = strlen(temp->entry->govSnmpRecordsGender);
	temp->entry->govSnmpRecordsDesignation_len = strlen(temp->entry->govSnmpRecordsDesignation);
	temp->entry->valid = 1;

	temp->next = (struct emp*)malloc(sizeof(struct emp));
	temp->next->prev = temp;
	temp = temp->next;
	temp->entry = (struct govSnmpRecordsTable_entry*)malloc(sizeof(struct govSnmpRecordsTable_entry));
	temp->entry->govSnmpRecordsEmployeeID = 4 ;
	strcpy(temp->entry->govSnmpRecordsName , "Gandhi");
	strcpy(temp->entry->govSnmpRecordsGender , "M");
	strcpy(temp->entry->govSnmpRecordsDesignation , "Director");
	temp->entry->govSnmpRecordsSalary = 2500000;
	temp->entry->govSnmpRecordsName_len = strlen(temp->entry->govSnmpRecordsName);
	temp->entry->govSnmpRecordsGender_len = strlen(temp->entry->govSnmpRecordsGender);
	temp->entry->govSnmpRecordsDesignation_len = strlen(temp->entry->govSnmpRecordsDesignation);
	temp->entry->valid = 1;

	temp->next = NULL;
	tail = temp;
		
}


/*
 * create a new row in the table 
 */
static struct govSnmpRecordsTable_entry *
govSnmpRecordsTable_createEntry(int dummy, long govSnmpRecordsEmployeeID)
{
       struct emp* current = tail;
    current->next = (struct emp*)malloc(sizeof(struct emp));
    
	if (!current->entry)
        return NULL;


  	current = current->next;
  	current->entry->govSnmpRecordsEmployeeID = govSnmpRecordsEmployeeID;
  	current->entry->valid = 1;
  	current->next = NULL;
  	tail = current;

    return tail->entry;
}

/*
 * remove a row from the table 
 */
static void
govSnmpRecordsTable_removeEntry(struct govSnmpRecordsTable_entry *entry)
{
   if (!entry)
        return;                 /* Nothing to remove */

    struct emp* search = header;
	if(search == NULL) 		//list empty
		return;

	do
	{
		//this skips the invalid ones;
		while(search->entry->valid != 1 || search->next == NULL)
			search = search->next;
		if(entry->govSnmpRecordsEmployeeID == search->entry->govSnmpRecordsEmployeeID)
		{
			//search->prev->next = search->next;
			//search->next->prev = search->prev;
			search->entry->valid = 0;
			break;
		}
		search = search->next;
	}while(search != tail);

    if (entry)
        SNMP_FREE(entry);       /* XXX - release any other internal resources */
}


/** determine the appropriate row for an exact request */
static struct govSnmpRecordsTable_entry *
govSnmpRecordsTable_get_entry(netsnmp_variable_list * indexes)
{
     struct govSnmpRecordsTable_entry *row = NULL;

     if (!indexes) 					// index can not be zero
        return;                 
     long* compare = indexes->val.integer;
     struct emp* search = header;
     if(search == NULL) 				//list empty
		return;

	do
	{ 	
		//this skips the invalid ones
		while(search->entry->valid != 1 && search->next != NULL)
			search = search->next;
		if( *compare  == search->entry->govSnmpRecordsEmployeeID)
		{
				return search->entry;
		}
		search = search->next;
	}while(search != NULL);
 
    /*
     * XXX - Use the 'indexes' parameter to retrieve the data
     * structure for the requested row, and return this. 
     */
    return row;
}
//to return the node having the employee entry in it as data
struct emp* govSnmpRecordsTable_get_node(long index)
{
	struct emp* node = header;
	
	if(node == NULL) 				//list empty
		return;

	do
	{ 	
		//this skips the invalid ones
		while(node->entry->valid != 1 && node->next != NULL)
			node = node->next;
		if( index  == node->entry->govSnmpRecordsEmployeeID)
		{
				return node;
		}
		node = node->next;
	}while(node != tail);
	return node;
}

/** determine the appropriate row for an fuzzy request */
static struct govSnmpRecordsTable_entry *
govSnmpRecordsTable_get_next_entry(netsnmp_handler_registration *reginfo,
                                   netsnmp_request_info *request,
                                   int column,
                                   netsnmp_variable_list * indexes)
{
    struct govSnmpRecordsTable_entry *row = NULL;
    oid             build_space[MAX_OID_LEN];
    size_t          build_space_len = 0;
    size_t          index_oid_len = 0;
    long index = *(indexes->val.integer);	
    
    struct emp* node = govSnmpRecordsTable_get_node(index);
    if(node == NULL) 
	row = NULL; 	//the list is empty or it does not have that index;
    else
	{
	 if(node->next == NULL)		//last node	
	   {	
		if(column >= MAX_COL)
			row = NULL;	//error referring to a non-existent column also
					//this is the last node and the last column 
		else{
		          // first employeeID
			*(indexes->val.integer) = 1;  
			row = govSnmpRecordsTable_get_entry(indexes);
			column++;							
		        if (column == 5)    // last column in integer (salary)
				indexes->type = ASN_INTEGER;
	            }
           }
	else	
	  {
		if(column > MAX_COL)
			row = NULL;
		else
			*(indexes->val.integer) += 1;		
			row = govSnmpRecordsTable_get_entry(indexes);
	  }				
	}

    /*
     * XXX - Use the 'indexes' parameter to identify the
     * next row in the table.... 
     */

    /*
     * XXX   .... update the 'indexes' parameter with the
     * appropriate index values ... 
     */

    /*
     * ... and update the requested OID to match this instance 
     */
    memcpy(build_space, reginfo->rootoid,       /* registered oid */
           reginfo->rootoid_len * sizeof(oid));
    build_space_len = reginfo->rootoid_len;
    build_space[build_space_len++] = 1; /* entry */
    build_space[build_space_len++] = column;    /* column */
    build_oid_noalloc(build_space + build_space_len,
                      MAX_OID_LEN - build_space_len, &index_oid_len,
                      NULL, 0, indexes);
    snmp_set_var_objid(request->requestvb, build_space,
                       build_space_len + index_oid_len);

    /*
     * Finally, return the data structure for this row 
     */
    return row;
}


/** handles requests for the govSnmpRecordsTable table */
static int
govSnmpRecordsTable_handler(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct govSnmpRecordsTable_entry *table_entry;
    int             ret;

    switch (reqinfo->mode) {
        /*
         * Read-support
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->govSnmpRecordsName,
                                         table_entry->
                                         govSnmpRecordsName_len);
                break;
            case COLUMN_GOVSNMPRECORDSGENDER:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->govSnmpRecordsGender,
                                         table_entry->
                                         govSnmpRecordsGender_len);
                break;
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->
                                         govSnmpRecordsDesignation,
                                         table_entry->
                                         govSnmpRecordsDesignation_len);
                break;
            case COLUMN_GOVSNMPRECORDSSALARY:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           govSnmpRecordsSalary);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    case MODE_GETNEXT:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_next_entry(reginfo, request,
                                                   table_info->colnum,
                                                   table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->govSnmpRecordsName,
                                         table_entry->
                                         govSnmpRecordsName_len);
                break;
            case COLUMN_GOVSNMPRECORDSGENDER:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->govSnmpRecordsGender,
                                         table_entry->
                                         govSnmpRecordsGender_len);
                break;
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->
                                         govSnmpRecordsDesignation,
                                         table_entry->
                                         govSnmpRecordsDesignation_len);
                break;
            case COLUMN_GOVSNMPRECORDSSALARY:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           govSnmpRecordsSalary);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
                /*
                 * or possibly 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              govSnmpRecordsName));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_GOVSNMPRECORDSGENDER:
                /*
                 * or possibly 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              govSnmpRecordsGender));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
                /*
                 * or possibly 'netsnmp_check_vb_type_and_size' 
                 */
                ret =
                    netsnmp_check_vb_type_and_max_size(request->requestvb,
                                                       ASN_OCTET_STR,
                                                       sizeof(table_entry->
                                                              govSnmpRecordsDesignation));
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_GOVSNMPRECORDSSALARY:
                /*
                 * or possibly 'netsnmp_check_vb_int_range' 
                 */
                ret = netsnmp_check_vb_int(request->requestvb);
                if (ret != SNMP_ERR_NOERROR) {
                    netsnmp_set_request_error(reqinfo, request, ret);
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_ERR_NOTWRITABLE);
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
            case COLUMN_GOVSNMPRECORDSGENDER:
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
            case COLUMN_GOVSNMPRECORDSSALARY:
                if (!table_entry) {
                    table_entry =
                        govSnmpRecordsTable_createEntry(0,
                                                        *table_info->
                                                        indexes->val.
                                                        integer);
                    if (!table_entry) {
                        netsnmp_set_request_error(reqinfo, request,
                                                  SNMP_ERR_RESOURCEUNAVAILABLE);
                        return SNMP_ERR_NOERROR;
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_FREE:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
            case COLUMN_GOVSNMPRECORDSGENDER:
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
            case COLUMN_GOVSNMPRECORDSSALARY:
                if (table_entry && !table_entry->valid) {
                    govSnmpRecordsTable_removeEntry(table_entry);
                }
                break;
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
                memcpy(table_entry->old_govSnmpRecordsName,
                       table_entry->govSnmpRecordsName,
                       sizeof(table_entry->govSnmpRecordsName));
                table_entry->old_govSnmpRecordsName_len =
                    table_entry->govSnmpRecordsName_len;
                memset(table_entry->govSnmpRecordsName, 0,
                       sizeof(table_entry->govSnmpRecordsName));
                memcpy(table_entry->govSnmpRecordsName,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->govSnmpRecordsName_len =
                    request->requestvb->val_len;
                break;
            case COLUMN_GOVSNMPRECORDSGENDER:
                memcpy(table_entry->old_govSnmpRecordsGender,
                       table_entry->govSnmpRecordsGender,
                       sizeof(table_entry->govSnmpRecordsGender));
                table_entry->old_govSnmpRecordsGender_len =
                    table_entry->govSnmpRecordsGender_len;
                memset(table_entry->govSnmpRecordsGender, 0,
                       sizeof(table_entry->govSnmpRecordsGender));
                memcpy(table_entry->govSnmpRecordsGender,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->govSnmpRecordsGender_len =
                    request->requestvb->val_len;
                break;
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
                memcpy(table_entry->old_govSnmpRecordsDesignation,
                       table_entry->govSnmpRecordsDesignation,
                       sizeof(table_entry->govSnmpRecordsDesignation));
                table_entry->old_govSnmpRecordsDesignation_len =
                    table_entry->govSnmpRecordsDesignation_len;
                memset(table_entry->govSnmpRecordsDesignation, 0,
                       sizeof(table_entry->govSnmpRecordsDesignation));
                memcpy(table_entry->govSnmpRecordsDesignation,
                       request->requestvb->val.string,
                       request->requestvb->val_len);
                table_entry->govSnmpRecordsDesignation_len =
                    request->requestvb->val_len;
                break;
            case COLUMN_GOVSNMPRECORDSSALARY:
                table_entry->old_govSnmpRecordsSalary =
                    table_entry->govSnmpRecordsSalary;
                table_entry->govSnmpRecordsSalary =
                    *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
                if (table_entry && !table_entry->valid) {
                    govSnmpRecordsTable_removeEntry(table_entry);
                } else {
                    memcpy(table_entry->govSnmpRecordsName,
                           table_entry->old_govSnmpRecordsName,
                           sizeof(table_entry->govSnmpRecordsName));
                    memset(table_entry->old_govSnmpRecordsName, 0,
                           sizeof(table_entry->govSnmpRecordsName));
                    table_entry->govSnmpRecordsName_len =
                        table_entry->old_govSnmpRecordsName_len;
                }
                break;
            case COLUMN_GOVSNMPRECORDSGENDER:
                if (table_entry && !table_entry->valid) {
                    govSnmpRecordsTable_removeEntry(table_entry);
                } else {
                    memcpy(table_entry->govSnmpRecordsGender,
                           table_entry->old_govSnmpRecordsGender,
                           sizeof(table_entry->govSnmpRecordsGender));
                    memset(table_entry->old_govSnmpRecordsGender, 0,
                           sizeof(table_entry->govSnmpRecordsGender));
                    table_entry->govSnmpRecordsGender_len =
                        table_entry->old_govSnmpRecordsGender_len;
                }
                break;
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
                if (table_entry && !table_entry->valid) {
                    govSnmpRecordsTable_removeEntry(table_entry);
                } else {
                    memcpy(table_entry->govSnmpRecordsDesignation,
                           table_entry->old_govSnmpRecordsDesignation,
                           sizeof(table_entry->govSnmpRecordsDesignation));
                    memset(table_entry->old_govSnmpRecordsDesignation, 0,
                           sizeof(table_entry->govSnmpRecordsDesignation));
                    table_entry->govSnmpRecordsDesignation_len =
                        table_entry->old_govSnmpRecordsDesignation_len;
                }
                break;
            case COLUMN_GOVSNMPRECORDSSALARY:
                if (table_entry && !table_entry->valid) {
                    govSnmpRecordsTable_removeEntry(table_entry);
                } else {
                    table_entry->govSnmpRecordsSalary =
                        table_entry->old_govSnmpRecordsSalary;
                    table_entry->old_govSnmpRecordsSalary = 0;
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry =
                govSnmpRecordsTable_get_entry(table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_GOVSNMPRECORDSNAME:
            case COLUMN_GOVSNMPRECORDSGENDER:
            case COLUMN_GOVSNMPRECORDSDESIGNATION:
            case COLUMN_GOVSNMPRECORDSSALARY:
                if (table_entry && !table_entry->valid) {
                    table_entry->valid = 1;
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the govSnmpRecordsTable table by defining its contents and how it's structured */
static void
initialize_table_govSnmpRecordsTable(void)
{
    const oid       govSnmpRecordsTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 100, 3, 1 };
    netsnmp_handler_registration *reg;
    netsnmp_table_registration_info *table_info;

    reg =
        netsnmp_create_handler_registration("govSnmpRecordsTable",
                                            govSnmpRecordsTable_handler,
                                            govSnmpRecordsTable_oid,
                                            OID_LENGTH
                                            (govSnmpRecordsTable_oid),
                                            HANDLER_CAN_RWRITE);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: govSnmpRecordsEmployeeID */
                                     0);

    table_info->min_column = COLUMN_GOVSNMPRECORDSNAME;
    table_info->max_column = COLUMN_GOVSNMPRECORDSSALARY;

    netsnmp_register_table(reg, table_info);

    /*
     * Initialise the contents of the table here 
     */
}

/** Initializes the govSnmp module */
void
init_govSnmp(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_govSnmpRecordsTable();
}
int
 main(void)
{
  netsnmp_ds_set_boolean(NETSNMP_DS_APPLICATION_ID, NETSNMP_DS_AGENT_ROLE, 1);

  init_agent("govSnmpAgt");
  init_govSnmp();
  init_snmp("govSnmpAgt");
   create();  

  int ret_val=0;
  while(1) {
        ret_val = agent_check_and_process(1);
        if (-1 == ret_val) {
            continue;
        }
    }

 return 0;
}
