/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GOVSNMP_H
#define GOVSNMP_H

/*
 * function declarations 
 */
void            init_govSnmp(void);
Netsnmp_Node_Handler handle_govSnmpNoPages;
Netsnmp_Node_Handler handle_govSnmpIntensity;
Netsnmp_Node_Handler handle_govSnmpStatus;

#endif                          /* GOVSNMP_H */
