/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GOVSNMP_H
#define GOVSNMP_H

/*
 * function declarations 
 */
int             send_govSnmpLessPages_trap(void);
int             send_govSnmpLowInk_trap(void);
int             send_govSnmpNotPrinting_trap(void);

#endif                          /* GOVSNMP_H */
