/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */
#ifndef GOVSNMP_H
#define GOVSNMP_H

void            init_govSnmp(void);

#endif                          /* GOVSNMP_H */
